### ISSUE TITLE
Archive 1 completed assignment in the done colum

### ISSUE THREAD

**Issue by Unweirdly** [Unweirdly/FirstDraft#28]

**Comment by jonitaylor513** [comment]
most of these are done

**Comment by jonitaylor513** [comment]
im doing them faster then your creating them

**Comment by Unweirdly** [comment]
Lol, I am just seeing what can be done. Might do this to the other NOOBS

**Comment by jonitaylor513** [comment]
i cant find the archive and im doing it mostly in github not waffle its easier

**Comment by jonitaylor513** [comment]
found it done
