### ISSUE TITLE
Buy Shower Towels

### ISSUE THREAD

**Issue by jonitaylor513** [Unweirdly/FirstDraft#29]

**Comment by Unweirdly** [comment]
@jonitaylor513 - What do you think of these 
https://www.walmart.com/ip/Better-Homes-and-Gardens-Thick-and-Plush-Solid-Bath-Collection/381454095

https://www.amazon.com/dp/B00Q7JFDKK/ref=cm_wl_huc_continue

**Comment by jonitaylor513** [comment]
I would prefer black to match the towels we already have please

**Comment by Unweirdly** [comment]
@jonitaylor513 

What about this ?

https://www.amazon.com/AmazonBasics-Fade-Resistant-6-Piece-Cotton-Set/dp/B00Q7JF38W/ref=sr_1_1_sspa?ie=UTF8&qid=1532808931&sr=8-1-spons&keywords=black+towels&psc=1

**Comment by jonitaylor513** [comment]
sure

**Comment by Unweirdly** [comment]
![Capture.JPG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b54057675aa950013b207ac/125516c66e82c728ace21e0d46cb958a379791accda5fd53b652fa912a5265296b51a17e24d5b629bd1028585c0e4bac41590a44fcf18e2daea42062c80d55b98e30063e937f03a6aa8316b500bf23894784b6bd824cc6e83a37aa.JPG)

**Comment by jonitaylor513** [comment]
Thank you
